# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Qsafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
	pod 'SwiftLint'
	
  # Pods for Qsafe

  target 'QsafeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QsafeUITests' do
    # Pods for testing
  end

end
